name: SimenAUVtest
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blas=2.111=mkl
  - blas-devel=3.9.0=11_win64_mkl
  - brotlipy=0.7.0=py37hcc03f2d_1001
  - ca-certificates=2021.5.30=h5b45459_0
  - cffi=1.14.6=py37hd8e9650_1
  - chardet=4.0.0=py37h03978a9_1
  - cloudpickle=1.6.0=py_0
  - cryptography=3.4.7=py37h20c650d_0
  - cudatoolkit=11.1.1=heb2d755_7
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py37hcc03f2d_3
  - dask-core=2021.9.0=pyhd8ed1ab_0
  - decorator=4.4.2=py_0
  - enum34=1.1.10=py37hc8dfbb8_2
  - ffmpeg=4.3.1=ha925a31_0
  - freetype=2.10.4=h546665d_1
  - fsspec=2021.8.1=pyhd8ed1ab_0
  - future=0.18.2=py37h03978a9_3
  - gym=0.19.0=py37h4038f58_0
  - imagecodecs-lite=2019.12.3=py37hda49f71_3
  - imageio=2.9.0=py_0
  - intel-openmp=2021.3.0=h57928b3_3372
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.3.2=py37h8c56517_0
  - libblas=3.9.0=11_win64_mkl
  - libcblas=3.9.0=11_win64_mkl
  - liblapack=3.9.0=11_win64_mkl
  - liblapacke=3.9.0=11_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.42.0=h8ffe710_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.4.3=py37h4a79c79_0
  - mkl=2021.3.0=hb70f87d_564
  - mkl-devel=2021.3.0=h57928b3_565
  - mkl-include=2021.3.0=hb70f87d_564
  - msys2-conda-epoch=20160418=1
  - networkx=2.6.3=pyhd8ed1ab_0
  - ninja=1.10.2=h5362a0b_0
  - numpy=1.21.2=py37h940b05c_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1l=h8ffe710_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py37h9386db6_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathlib=1.0.1=py37h03978a9_4
  - pillow=8.3.1=py37h4fa10fc_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pooch=1.5.1=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyglet=1.5.16=py37h03978a9_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py37h03978a9_3
  - python=3.7.10=h7840368_101_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.8.2=py3.7_cuda11.1_cudnn8_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py37hec80d1f_3
  - pyyaml=5.4.1=py37hcc03f2d_1
  - requests=2.26.0=pyhd8ed1ab_0
  - scikit-image=0.18.3=py37h9386db6_0
  - scipy=1.7.1=py37hb6553fb_0
  - setuptools=58.0.4=py37h03978a9_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h8ffe710_1
  - tbb=2021.3.0=h2d74725_0
  - tifffile=2019.7.26.2=py37_0
  - tk=8.6.11=h8ffe710_1
  - toolz=0.11.1=py_0
  - torchaudio=0.8.2=py37
  - torchvision=0.9.2=py37_cu111
  - tornado=6.1=py37hcc03f2d_1
  - typing_extensions=3.10.0.0=pyha770c72_0
  - ucrt=10.0.20348.0=h57928b3_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wheel=0.37.0=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=py37h03978a9_2
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - absl-py==0.13.0
    - atari-py==0.2.9
    - cachetools==4.2.2
    - certifi==2021.5.30
    - charset-normalizer==2.0.6
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.40.0
    - idna==3.2
    - importlib-metadata==4.8.1
    - markdown==3.3.4
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - protobuf==3.18.0
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - stable-baselines3==1.2.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - werkzeug==2.0.1
    - zipp==3.5.0
prefix: C:\Users\Thomas\anaconda3\envs\SimenAUVtest
